### PR TITLE
issue#3 Added devise gem 

### LINKED ISSUE #3: Create User model and table
(should be done after issue #2 Create starter repo)

Create User model, table, controller (optional, but if you're scaffolding...you may as well).
User table should have columns:

- name (username?)
- email
- password

Use Devise gem.

### PR DESCRIPTION
**Pull request by Mariela-t**

### CODE REVIEW

**Comment by Mariela-t** [comment]
Not sure if I should add a controller for user even if we are using the devise gem?

**Comment by DianaLiao** [comment]
> Not sure if I should add a controller for user even if we are using the devise gem?

I think it's okay to see what devise gives you out of the box and then we can decide later if we need another controller once you start manually testing.

**Comment by JacinthaDev** [comment]
LGTM

**Review by JacinthaDev — APPROVED** [review]
LGTM

**Review by christopher-ga — APPROVED** [review]
LGTM

**Pull request merged**
