### PR TITLE
#6 Added comment model

### LINKED ISSUE #6: Create Comment model and table
(should be done after #4 Create Entry)

columns include:

- user_id (foreign key)
- entry_id (foreign key)
- text

Add appropriate relationships into User, Entry, and Comment models

### PR DESCRIPTION
**Pull request by Mariela-t**

### CODE REVIEW

**Comment by Mariela-t** [comment]
Are we adding the controllers yet?

**Comment by christopher-ga** [comment]
> Are we adding the controllers yet?

I think we can make that another ticket? I was thinking the same thing for the friendships table stuff.

**Review by christopher-ga — APPROVED** [review]
LGTM

**Review by JacinthaDev — COMMENTED** [review]
LGTM

**Review by JacinthaDev — APPROVED** [review]

**Pull request merged**
